### ISSUE TITLE
Unable to generate REST API documentation

### ISSUE THREAD

**Issue by aaabdallah** [keycloak/keycloak-documentation#1318] opened 2021-11-28 06:41 UTC
### Describe the bug

Recently I cloned the keycloak-documentation, switched to tag 4.8.3.Final, and followed the instructions. It generates all documentation except the REST API manual.
The same thing happens for tag 16.0.0, 5.0.0, and others.

I posted a question about this at https://github.com/keycloak/keycloak/discussions/8913

Is there a bug in the build procedure?

### Version

4.8.3

### Expected behavior

It should generate the documentation

### Actual behavior

The REST API manual is not generated (others are however).

### Anything else?

Note that searching via grep in keycloak-documentation for phrases that are clearly in the documentation for the REST API (I picked phrases from the online documentation) gives no results. It is as if the raw material is simply NOT in keycloak-documentation for the REST API...?

**Comment by stianst** [comment] 2021-12-01 17:35
Closing this as it's not a bug, and there's already an open question for this topic.

**Closed as completed by stianst** 2021-12-01 17:35 UTC
Labels: kind/bug, status/triage

**Comment by djeikyb** [comment] 2022-06-17 00:22
@stianst Why is this not a bug? Where is the open question? Most importantly, where is the rest documentation? I'm stuck on 4.4 and it'd be great to have the rest api docs, even if I have to build them myself.

**Comment by djeikyb** [comment] 2022-06-17 00:24
@stianst Why is this not a bug? Is this project not supposed to have the api docs? More importantly, where is the rest api documentation? I'm stuck on 4.4 and it'd be great to have the rest api docs, even if I have to build them myself.

**Comment by aaabdallah** [comment] 2022-06-17 01:44
I never resolved this. And I am still in need of 4.8.3 REST API documentation.
